In [5]:
import numpy as np

# ----------------------------------------
# Define function
# ----------------------------------------
def calc_linear_regression_model(w, b, x):
    return np.dot(w, x) + b


def calc_cost_function_partial_derivative_w(x_train: np.ndarray, y_train: np.ndarray, w: np.ndarray, b: float):
    m = x_train.shape[0]
    total = 0

    for i in range(m):
        x_i = x_train[i]
        y_i = y_train[i]
        y_hat_i = calc_linear_regression_model(w, b, x_i)
        total = total + ((y_hat_i - y_i) * x_i)

    return 1 / m * total


def calc_cost_function_partial_derivative_b(x_train: np.ndarray, y_train: np.ndarray, w: float, b: float):
    m = x_train.shape[0]
    total = 0

    for i in range(m):
        x_i = x_train[i]
        y_i = y_train[i]
        y_hat_i = calc_linear_regression_model(w, b, x_i)
        total = total + (y_hat_i - y_i)

    return 1 / m * total


def find_optimum_w_and_b(x_train: np.ndarray, y_train: np.ndarray, alpha, w_init: np.ndarray, b_init, batch_count):
    w_optimum = w_init
    b_optimum = b_init
    m = x_train.shape[0]
    
    for iter in range(batch_count):
        w_temp = w_optimum - alpha * calc_cost_function_partial_derivative_w(x_train, y_train, w_optimum, b_optimum)
        b_temp = b_optimum - alpha * calc_cost_function_partial_derivative_b(x_train, y_train, w_optimum, b_optimum)
        w_optimum = w_temp
        b_optimum = b_temp

    return w_optimum, b_optimum


# ----------------------------------------
# Running
# ----------------------------------------
x_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])
alpha = 5.0e-7
w_init = np.zeros_like([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
b_init = 0
batch_count = 1000

w_optimum, b_optimum = find_optimum_w_and_b(x_train, y_train, alpha, w_init, b_init, batch_count)


print(f"x_train\n {x_train}\n")
print(f"y_train\n {y_train}\n")
print(f"Optimum w\n{w_optimum}\n")
print(f"Optimum b\n{b_optimum}\n")


x_train
 [[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]

y_train
 [460 232 178]

Optimum w
[ 0.20396569  0.00374919 -0.0112487  -0.0658614 ]

Optimum b
-0.002235407530932535

